server:
  port: 8080
  context-path: /mbr

  session:
    timeout: 3

spring:
  datasource:
    url: jdbc:mariadb://10.178.230.98:3306/hotspot_member
#    url: jdbc:mariadb://169.56.96.234:3306/hotspot_member
#    url: jdbc:mariadb://localhost:3306/hotspot_member
    driverClassName: org.mariadb.jdbc.Driver
    username: hotspot_member_user
    password: hotspot_member_user
     
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true 

  session: 
    store-type: redis

#spring.redis.cluster.nodes: 127.0.0.1:6379
#spring.session.store-type : redis

#  redis:
##    host: 127.0.0.1
##    host: O6L6ATk7Be@10.178.230.75
#    host: 10.178.230.75
#    port: 6379

  redis:
    uri: redis://O6L6ATk7Be@10.178.230.75:6379
#    uri: redis://O6L6ATk7Be@169.56.96.235:6379
#    uri: redis://localhost:6379    
    timeout: 3


logging:
  level: 
    org.hibernate.type: info