apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hotspot-mbr # deployment name -> kubectl get deployment
  labels:
    app: hotspot-mbr
spec:
  replicas: 1 # number of pod
  selector:
    matchLabels:
      app: hotspot-mbr
  template:
    metadata:
      labels:
        app: hotspot-mbr
    spec:
      containers:
      - name: sample-gs-spring-boot-docker
#        image: dep-dev-registry.cloudzcp.io/hotspot/gs-spring-boot-docker:32
        image: dep-dev-registry.cloudzcp.io/sample/hotspot-mbr:1
      imagePullSecrets:
      - name: jonas-secret 
#        ports:
#        - containerPort: 8080